/*  =========================================================================
    curve_classes - private header file

    Copyright (c) the Contributors as noted in the AUTHORS file.         
    This file is part of the Curve authentication and encryption library.
                                                                         
    This Source Code Form is subject to the terms of the Mozilla Public  
    License, v. 2.0. If a copy of the MPL was not distributed with this  
    file, You can obtain one at http://mozilla.org/MPL/2.0/.             
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef CURVE_CLASSES_H_INCLUDED
#define CURVE_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/curve.h"

//  Internal API

#endif
